---
title: "performance_cswea"
output: 
  html_document
    number_sections: TRUE
    code_folding: hide
    toc: true
    toc_float: true

---

# Set up
```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(ggplot2)
library(MetBrewer)
library(lubridate)
library(reshape2)
library(zoo)

```


# Data read in
```{r read in}
setwd("~/Github/wssc")
data_path <- "./performance/data/220510_performance.xlsx"

# data read in and initializing ----------
air <- read_excel(data_path,sheet="airflow")
se1 <- read_excel(data_path,sheet="se_1")
se2 <- read_excel(data_path,sheet="se_2")
se3 <- read_excel(data_path,sheet="se_3")
se4 <- read_excel(data_path,sheet="se_4")

se1$train <- "test"
se2$train <- "se2"
se3$train <- "se3"
se4$train <- "se4"

# subset to dates of interest - 3/21/21 to now
se_test <- se1 %>% filter(date >= "2021-03-22")
se_control_all <- bind_rows(se2,se3,se4) %>%
  filter(date >= "2021-03-22")

# mark period before and after pilot start
air$period <- cut.POSIXt(air$date, 
  breaks = as.POSIXct(as.Date(c("1970-01-01","2021-03-22","9999-12-31"))),
  labels = c("before pilot","pilot study"))
air <- air %>%
  filter(date >= "2020-03-01")

```

# Cleaning
```{r cleaning secondary eff data}
se_control <- se_control_all %>%
  group_by(date) %>%
  summarize(TP=mean(TP),
            NH4=mean(NH4),
            NOx=mean(NOx))

se_control$train <- "control"

se_all <- bind_rows(se_test,se_control)

```




# Analysis
## Summary statistics control vs test
### Control
```{r summary stats control}
summary(se_control)
quantile(se_control$TP,c(.1,.5,.9),na.rm=TRUE)
quantile(se_control$NH4,c(.1,.5,.9),na.rm=TRUE)
quantile(se_control$NOx,c(.1,.5,.9),na.rm=TRUE)
```

### Test
```{r summary stats test}
summary(se_test)
quantile(se_test$TP,c(.1,.5,.9),na.rm=TRUE)
quantile(se_test$NH4,c(.1,.5,.9),na.rm=TRUE)
quantile(se_test$NOx,c(.1,.5,.9),na.rm=TRUE)
```
## Summary stats air flow before and after pilot
### Control before and after pilot study
```{r air control}
air %>%
  filter(period=="before pilot") %>%
  select(AT2) %>%
  summary()

air %>%
  filter(period=="pilot study") %>%
  select(AT2) %>%
  summary()

```



### Test before and after pilot study
```{r air test}
air %>%
  filter(period=="before pilot") %>%
  select(AT1) %>%
  summary()

air %>%
  filter(period=="pilot study") %>%
  select(AT1) %>%
  summary()


```




## Plotting
```{r formatting secondary eff before plotting, include=FALSE}
se_all_long <- melt(se_all,id.vars=c("date","train"))
se_all_long$date <- as_date(se_all_long$date)

```

```{r plotting P performance}

plot_p <- ggplot(data=se_all_long,aes(x=date,y=value,color=train,shape=train)) +
  geom_point(data=subset(se_all_long,variable=="TP"),alpha=0.8) +
  theme_classic() +
  labs(y="Effluent Total P (mgP/L)",x="Date") +
  scale_x_date(date_labels="%Y-%m",limits=c(as_date("2021-03-22"),as_date("2022-05-01"))) +
  ylim(0,0.5) +
  scale_color_manual(values=c("#8282AA","#B36560")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position="none")

ggsave("p_comparison.tiff",plot=plot_p,width=5.5,height=5,units="in",dpi=300,scale=0.5)
```


```{r}
ggplot(data=se_all_long,aes(x=date,y=value,color=train,shape=train)) +
  geom_point(data=subset(se_all_long,variable=="NH4"),alpha=0.8) +
  theme_classic() +
  labs(y="Effluent NH4 (mgN/L)",x="Date") +
  scale_x_date(date_labels="%Y-%m",limits=c(as_date("2021-03-22"),as_date("2022-05-01"))) +
  ylim(0,0.5) +
  scale_color_manual(values=c("#8282AA","#B36560")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        legend.position="none")
```



```{r air cleaning before plotting, include=FALSE}
air$AT1_ave <- rollapply(air$AT1,7,mean,na.rm=TRUE,partial = TRUE)
air$AT2_ave <- rollapply(air$AT2,7,mean,na.rm=TRUE,partial = TRUE)
air_long <- melt(air,id.vars=c("date","period"))
air_long$date <- as_date(air_long$date)

```


```{r plotting airflow}

plot_air <- ggplot(data=air_long,aes(x=date,y=value,color=variable)) +
  geom_rect(data=NULL,
            aes(xmin=as_date("2020-03-01"),xmax=as_date("2021-03-22"),ymin=-Inf,ymax=Inf),
            color="lightgrey",fill="lightgrey",alpha=0.1) + 
  geom_point(data=subset(air_long,variable=="AT1" | variable=="AT2"),alpha=0.6) +
  geom_line(data=subset(air_long,variable=="AT1_ave" | variable=="AT2_ave"),size=1.5) +
  theme_classic() +
  ylim(0,6000) +
  labs(title="",x="Date",y="Airflow to basin (SCFM)") +
  scale_x_date(breaks="4 months",date_labels="%Y-%m") +
  scale_color_manual(values=met.brewer("Cassatt1",4)) +
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1),
        legend.position="none")
  
ggsave("airflow_comparison.tiff",plot=plot_air,width=10,height=7,units="in",dpi=300,scale=0.5)

```

